# Generated by Django 5.0.2 on 2024-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_motto_mottotranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mottotranslation',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
