# Generated by Django 5.0.2 on 2024-02-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mottotranslation_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mottotranslation',
            name='body',
        ),
        migrations.AlterUniqueTogether(
            name='mottotranslation',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Motto',
        ),
        migrations.DeleteModel(
            name='MottoTranslation',
        ),
    ]
