# Generated by Django 5.0.2 on 2024-02-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_mottotranslation_master_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformTranslation',
        ),
    ]
