# Generated by Django 5.0.2 on 2024-02-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_telegramgroup_bot_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramGroup',
            new_name='Telegram',
        ),
    ]
